@API_URL = http://localhost:5000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmU1NjVlMzkxOWM0ZjlmNDcyOGI1N2IiLCJuYW1lIjoiUm9iZXJ0IiwiZW1haWwiOiJyb2JlcnRAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU5MjA1NzU5LCJleHAiOjE2NTkyMjM3NTl9.LY5Maapbo4qFjekvis1p1kSpDSnW5u290LFfwWndXbQ 

### Users all
GET {{API_URL}}/user
Authorization: {{TOKEN}}

### Admin Route
GET {{API_URL}}/user/admin
Authorization: {{TOKEN}}

### User single
GET {{API_URL}}/user
Authorization: {{TOKEN}}

### Signup
POST {{API_URL}}/user
Content-Type: application/json

{
  "name": "Albert",
  "email": "albert@gmail.com",
  "password": "albert" 
}

### Login
POST {{API_URL}}/user/login
Content-Type: application/json

{
  "email": "robert@gmail.com",
  "password": "robert" 
}

### if create todo
POST {{API_URL}}/todo
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "titles": "Code some frontend for JWT"
}